# Generated by Django 5.0.1 on 2024-01-14 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='sword',
            name='cost',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderContains', models.CharField(max_length=200)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('idCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_api.customer')),
            ],
        ),
    ]
