# Generated by Django 5.0.1 on 2024-01-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0002_customer_sword_cost_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sword',
            name='user',
        ),
    ]
