# Generated by Django 5.0.1 on 2024-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0003_remove_sword_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='1234', max_length=10),
        ),
    ]
