# Generated by Django 5.0.1 on 2024-01-14 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0004_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nickname',
        ),
    ]
