# Generated by Django 5.0.1 on 2024-01-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0006_alter_sword_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword',
            name='name',
            field=models.CharField(max_length=180, unique=True),
        ),
    ]
