# Generated by Django 5.0.1 on 2024-01-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0007_alter_sword_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sword',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
