# Generated by Django 5.0.1 on 2024-01-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0008_alter_sword_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idCustomer',
            field=models.IntegerField(),
        ),
    ]
