# Generated by Django 5.0.1 on 2024-01-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_api', '0010_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('damage', models.IntegerField()),
                ('completed', models.CharField(max_length=180)),
                ('range', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sword',
            name='sharpness',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
